### ISSUE TITLE
Does not work with slim templater

### ISSUE THREAD

**Issue by adrianov** [balinterdi/i15r#41]
```
$ i15r /path/to/app/views/shared/_my_account.html.slim -n
Running in dry-run mode
/path/to/app/views/shared/_my_account.html.slim:

/home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r/pattern_matcher.rb:36:in `const_get': uninitialized constant SlimTransformer (NameError)
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r/pattern_matcher.rb:36:in `initialize'
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r.rb:84:in `new'
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r.rb:84:in `sub_plain_strings'
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r.rb:79:in `internationalize_file'
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r.rb:99:in `block in internationalize!'
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r.rb:99:in `each'
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/lib/i15r.rb:99:in `internationalize!'
    from /home/adrianov/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/i15r-0.5.5/bin/i15r:56:in `<top (required)>'
    from /home/adrianov/.rbenv/versions/2.2.3/bin/i15r:23:in `load'
    from /home/adrianov/.rbenv/versions/2.2.3/bin/i15r:23:in `<main>'
```

**Comment by ACPK** [comment]
@adrianov - I know it's been a year and a half since you filed this issue, but did you figure out a solution?

**Comment by balinterdi** [comment]
Sorry for not replying on that one earlier but I don't have the time any more to maintain the gem.

Regarding this issue, to make it work, one would have to define a `SlimTransformer` class and define its `transform` method (see `ErbTransformer` and `HamlTransformer` in the `pattern_matcher.rb` file.

If any of you feels like implementing it, I'd be more than happy to merge it back in and release a new gem version.
